version: '3'

services:
  db_aristotel:
    image: postgres:12.2
    environment:
        POSTGRES_DB: db_aristotel
        POSTGRES_USER: aristoteluser
        POSTGRES_PASSWORD: aristotelpass
  web_aristotel:
    build: .
    command: python manage.py runserver 0.0.0.0:2000
    volumes:
      - .:/code
    ports:
      - "2000:2000"
    depends_on:
      - db_aristotel
    env_file:
      - ./.env.dev

