version: '3'

services:

  mediadb:
    container_name: tezdb
    image: postgres:12.2
    environment:
      POSTGRES_DB: db_media
      POSTGRES_USER: media_user
      POSTGRES_PASSWORD: media_pass

  mediaweb:
    container_name: mediaweb
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/code
    ports:
      - "7000:7000"
    depends_on:
      - mediadb
